/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtualpetpanda;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        boolean deadPanda = false;
        Scanner input = new Scanner(System.in);
        VirtualPanda pan = new VirtualPanda(10, 10, 10);
        int panHungerLevel = pan.getHunger();
        int panThirstLevel = pan.getThirst();
        int panBoredomLevel = pan.getBoredom();
        System.out.println("Meet Pan, the panda! \n - -\n(o.o)\n.. ..");
        System.out.println("He is very high maintenance.");
        System.out.println("If his hunger, thirst, or boredom reaches 100, he will die.");
        System.out.println("...& you will be a panda murderer (but no pressure)!");

        do {
            System.out.println("What would you like to do for Pan?");
            System.out.println("1 -- Feed him pandan toast");
            System.out.println("2 -- Give him a matcha latte");
            System.out.println("3 -- Play with him on the bamboo slide");
            int userInput = input.nextInt();
            if (panHungerLevel >= 100 || panThirstLevel >= 100 || panBoredomLevel >= 100) {
                System.out.println("  " +
                        "  _____ \n" +
                        " /     \\ \n" +
                        "| () () | \n" +
                        " \\ ^  / \n" +
                        "  |||||");
                deadPanda = true;
                System.out.println("You know pandas are endangered, right?");
                System.out.println("Yeesh, I guess not everyone is an animal lover.");
            }
            if (userInput == 1) {
                panHungerLevel = pan.feed(pan);
                System.out.println("Current hunger level: " + panHungerLevel + " out of 100");
            } else if (userInput == 2) {
                panThirstLevel = pan.drink(pan);
                System.out.println("Current thirst level: " + panThirstLevel + " out of 100");

            } else if (userInput == 3) {
                panBoredomLevel = pan.play(pan);
                System.out.println("Current boredom level: " + panBoredomLevel + " out of 100");

            }
        } while (!deadPanda);
        input.close();
    }
}
