/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtualpetpanda;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        boolean deadPanda = false;
        Scanner input = new Scanner(System.in);
        VirtualPanda pan = new VirtualPanda(10, 10, 10);
        pan.startCloserToDeath();
        System.out.println("Meet Pan, the panda!");
        System.out.println("");
        System.out.println("  {__}____{__}");
        System.out.println("  /          \\  ");
        System.out.println("  [ (@)     (@)  ");
        System.out.println("   \\   ( x ) / ");
        System.out.println("  < [       ] >");
        System.out.println("");
        System.out.println("He is very high maintenance.");
        System.out.println("If his hunger, thirst, or boredom reaches 100, he will die.");
        System.out.println("...& you will be a panda murderer (but no pressure)!");
        System.out.println("");

        do {
            System.out.println("What would you like to do for Pan?");
            System.out.println("1 -- Feed him pandan toast");
            System.out.println("2 -- Give him a matcha latte");
            System.out.println("3 -- Play with him on the bamboo slide");
            int userInput = input.nextInt();
            if (pan.getHunger() >= 100 || pan.getThirst() >= 100 || pan.getBoredom() >= 100) {
                System.out.println("");
                System.out.println("  {__}____{__}");
                System.out.println("  /          \\  ");
                System.out.println("  [ (X)     (X)  ");
                System.out.println("   \\   ( x ) / ");
                System.out.println("  < [  dead  ] >");
                System.out.println("");
                deadPanda = true;
                System.out.println("You know pandas are endangered, right?");
                System.out.println("Yeesh, I guess not everyone is an animal lover.");
            } else if (userInput == 1) {
                pan.feed();
                System.out.println("Current hunger level: " + pan.getHunger() + " out of 100");
                System.out.println("Current thirst level: " + pan.getThirst() + " out of 100");
                System.out.println("Current boredom level: " + pan.getBoredom() + " out of 100");
            } else if (userInput == 2) {
                pan.drink();
                System.out.println("Current thirst level: " + pan.getThirst() + " out of 100");
                System.out.println("Current hunger level: " + pan.getHunger() + " out of 100");
                System.out.println("Current boredom level: " + pan.getBoredom() + " out of 100");

            } else if (userInput == 3) {
                pan.play();
                System.out.println("Current boredom level: " + pan.getBoredom() + " out of 100");
                System.out.println("Current hunger level: " + pan.getHunger() + " out of 100");
                System.out.println("Current thirst level: " + pan.getThirst() + " out of 100");
            }
        } while (!deadPanda);
        input.close();
    }
}
